apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hystrix
spec:
  rules:
  - host: hystrix.k8s.com
    http:
      paths:
      - path: /
        backend:
          serviceName: hystrix
          servicePort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: hystrix
spec:
  type: ClusterIP
  selector:
    app: spring-cloud-hystrix
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spring-cloud-hystrix
  labels:
    app: spring-cloud-hystrix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-cloud-hystrix
  template:
    metadata:
      labels:
        app: spring-cloud-hystrix
        version: latest
    spec:
      hostname: hystrix
      subdomain: hystrix
      containers:
      - name: spring-cloud-hystrix
        image: ssipflow/spring-cloud-hystrix:latest
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: dev
        ports:
        - name: http
          containerPort: 8080